// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxxxxx',
    appId: 'xxxxxxxxxxxxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxxxxxxxxxxx',
    projectId: 'xxxxxxxxxxxxxxxxxxx',
    authDomain: 'xxxxxxxxxxxxxxxxxxx',
    databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: 'xxxxxxxxxxxxxxxxxxx',
    measurementId: 'xxxxxxxxxxxxxxxxxxx',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvlizwHHSIrmqCKbNKFaUvo7-zzh0Okik',
    appId: '1:847692729333:android:a7e62988ec3e7bf56eeebc',
    messagingSenderId: '847692729333',
    projectId: 'chat-app-flutter-69397',
    databaseURL: '',
    storageBucket: 'chat-app-flutter-69397.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARPUMy9jzKJ9poBFQ9_BYaPdpr9vfiuxQ',
    appId: '1:847692729333:ios:d92482bd73e874d06eeebc',
    messagingSenderId: '847692729333',
    projectId: 'chat-app-flutter-69397',
    databaseURL: '',
    storageBucket: 'chat-app-flutter-69397.firebasestorage.app',
    androidClientId: '',
    iosClientId: '',
    iosBundleId: 'com.example.chatApp',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'xxxxxxxxxxxxxxxxxxx',
  //   appId: 'xxxxxxxxxxxxxxxxxxx',
  //   messagingSenderId: 'xxxxxxxxxxxxxxxxxxx',
  //   projectId: 'xxxxxxxxxxxxxxxxxxx',
  //   databaseURL: 'xxxxxxxxxxxxxxxxxxx',
  //   storageBucket: 'xxxxxxxxxxxxxxxxxxx',
  //   androidClientId: 'xxxxxxxxxxxxxxxxxxx',
  //   iosClientId: 'xxxxxxxxxxxxxxxxxxx',
  //   iosBundleId: 'xxxxxxxxxxxxxxxxxxx',
  // );
}
